"""initial

Revision ID: 685e742a7975
Revises: 
Create Date: 2023-03-08 22:58:39.248152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685e742a7975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
